### ISSUE TITLE
1.6 beta breaks build

### ISSUE THREAD

**Issue by timothybone** [nf/sigourney#13]
For now the workaround is to allow go to still send go pointers to cgo (I guess?), i.e. revert to GO 1.5

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/gordonklaus/portaudio._cgoCheckPointer1(0x4311a80, 0xc8200fe100, 0x0, 0x0, 0x0, 0x42f25a0)
	??:0 +0x4d
github.com/gordonklaus/portaudio.OpenStream(0x0, 0x0, 0x0, 0xc82006c3c0, 0x1, 0xd78f88, 0x40e5888000000000, 0x100, 0x0, 0xc820055c18, ...)
	/Users/timothybone/work/src/github.com/gordonklaus/portaudio/portaudio.go:504 +0x3d1
github.com/gordonklaus/portaudio.OpenDefaultStream(0x0, 0x1, 0x40e5888000000000, 0x100, 0xc820055c18, 0x1, 0x1, 0x44451a0, 0x0, 0x0)
	/Users/timothybone/work/src/github.com/gordonklaus/portaudio/portaudio.go:538 +0x24a
github.com/nf/sigourney/audio.(*Engine).Start(0xc82006c2a0, 0x0, 0x0)
	/Users/timothybone/work/src/github.com/nf/sigourney/audio/engine_cgo.go:24 +0x13d
main.demo(0x0, 0x0)
	/Users/timothybone/work/src/github.com/nf/sigourney/demo.go:29 +0xd1
main.main()
	/Users/timothybone/work/src/github.com/nf/sigourney/main.go:51 +0x9e

**Comment by nf** [comment]
If the portaudio maintainers don't fix it, we might have to switch to a
different package for talking to the audio card.

**Comment by jaredfolkins** [comment]
There is a work in progress. I was able to get Sigourney working with my branch.

https://github.com/gordonklaus/portaudio/issues/7
